# -*- coding: utf-8 -*-
"""CalculoEntradaaZero-ASL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UIRWD4E44x1j52x-t_GCrrKtJJerj2lZ
"""

#Resposta a Entrada Zero
from math import *
from sympy import *
import numpy as np
 
print('Calculando Resposta a entrada zero de grau 2\n')
a = float(input('Numero com D^2: '))
b = float(input('Numero com D: '))
c = float(input('Valor de c: '))
i = float(input('Valor inicial: '))
i2 = float(input('Derivada do Valor inicial: '))
 
D = (b**2 - 4*a*c)
lambda1 = (-b + D**(1/2)) / (2*a)
lambda2 = (-b - D**(1/2)) / (2*a)
 
if lambda1 != lambda2:
  arr = np.array([[1,1],[lambda1,lambda2]])
  arr2 = np.array([[i],[i2]])
  arr = np.linalg.inv(arr)
  (c1,c2) = np.dot(arr,arr2)
  print("c2 = {} e c1 = {}". format(c1, c2))
if lambda1 == lambda2:
  c1 = i
  c2 = i2 - c1*lambda1
  print("c2 = {} e c1 = {}". format(c1, c2))

lambda1

D

lambda2